# 规范文档参考:
# 中文：https://github.com/Serverless-Devs/Serverless-Devs/blob/master/spec/zh/0.0.2/serverless_package_model/3.package_model.md#应用模型规范
# English: https://github.com/Serverless-Devs/Serverless-Devs/blob/master/spec/en/0.0.2/serverless_package_model/3.package_model.md#Application-model-specification
# --------------
# Package 开发发布最佳实践:
#   - [社区讨论 #62](https://github.com/Serverless-Devs/Serverless-Devs/discussions/62);
#   - [社区讨论 #407](https://github.com/Serverless-Devs/Serverless-Devs/discussions/407);
#   - [社区讨论 #439](https://github.com/Serverless-Devs/Serverless-Devs/discussions/439);

Type: Application
Name: paddlePyramidBox
Provider:
  - 阿里云
Version: 0.0.30
Description: 本应用基于百度开源的 PaddlePaddle 项目，PyramidBox-Lite是基于2018年百度发表于计算机视觉顶级会议ECCV 2018的论文PyramidBox而研发的轻量级模型，模型基于主干网络FaceBoxes，对于光照、口罩遮挡、表情变化、尺度变化等常见问题具有很强的鲁棒性。
HomePage: https://github.com/duolabmeng6/paddlePyramidBox
Tags: #标签详情
  - 人工智能
  - 人脸检测
Category: 人工智能 # 基础云服务/Web框架/Web应用/人工智能/音视频处理/图文处理/监控告警/大数据/IoT/新手入门/其他
Service:
  函数计算:
    Authorities:
      - AliyunFCFullAccess
      - AliyunContainerRegistryFullAccess
    Runtime: custom container
Parameters:
  type: object
  additionalProperties: false # 不允许增加其他属性
  required: # 必填项
    - region
    - serviceName
    - functionName
    - memorySize
  properties:
    region:
      title: 地域
      type: string
      default: cn-shenzhen
      description: 创建应用所在的地区
      enum:
        - cn-shenzhen
        - cn-beijing
        - cn-hangzhou
        - cn-shanghai
        - cn-qingdao
        - cn-zhangjiakou
        - cn-huhehaote
        - cn-chengdu
        - cn-hongkong
    serviceName:
      title: 服务名
      type: string
      default: paddlePyramidBox
      description: 服务名称，只能包含字母、数字、下划线和中划线。不能以数字、中划线开头。长度在 1-128 之间
    functionName:
      title: 函数名
      type: string
      default: paddlePyramidBox
      description:  函数名称，只能包含字母、数字、下划线和中划线。不能以数字、中划线开头。长度在 1-64 之间
    memorySize:
      title: 内存规格
      type: string
      default: 1024
      description:  内存规格，单位为 MB，默认为 1024 MB